<!--
==========================================================================
SnomControl - A General purpose web control system for Snom VoIP Phones
Copyright (C) 2014 Ashley Unwin

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
==========================================================================
-->



<?php
$mac=$_POST['mac'];
$type=$_POST['type'];
$myFile = "snom$type-$mac.htm";
$fh = fopen($myFile, 'w') or die("Doh you have a problem. NOOOOO!!!");

$string = "# Snom Configuration:Generated By SnomControl.AshleyUnwin.com"
. PHP_EOL ;


// Get values sent to page from user form input
foreach ($_POST as $key => $value) {
    echo $key. " => " .$value.'<br/>';
	$string = $string. PHP_EOL .$key. ": ".$value;
}
echo "String => " . $string;


fwrite($fh, $string);
fclose($fh);

Echo "Completed";

Echo "<br><br><a href='snom$type-$mac.htm'>View Generated Config File</a>";

?>




