<?php
$mac=$_POST['mac'];
$type=$_POST['type'];
$myFile = "snom$type-$mac.htm";
$fh = fopen($myFile, 'w') or die("Doh you have a problem. NOOOOO!!!");

$string = "# Snom Configuration:Generated By SnomControl.AshleyUnwin.com"
. PHP_EOL ;


// Get values sent to page from user form input
foreach ($_POST as $key => $value) {
    echo $key. " => " .$value.'<br/>';
	$string = $string. PHP_EOL .$key. ": ".$value;
}
echo "String => " . $string;


fwrite($fh, $string);
fclose($fh);

Echo "Completed";

Echo "<br><br><a href='snom$type-$mac.htm'>View Generated Config File</a>";

?>




